version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=literature
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development_pass
    ports:
      - "3306:3306"

  php:
    container_name: php
    build: ./php
    volumes:
      - ./../:/srv
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./../:/srv
      - ./nginx/default.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - mysql
    working_dir: /srv